# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # golang: "1.19"
    python: "3.11"
    rust: "1.70"
    # nodejs: "18"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
  #   - method: pip
  #     path: .
  #     extra_requirements:
  #       - docs
  #   - method: pip
  #     path: another/package
  # system_packages: true

# search:
#   ranking:
#     api/v1/*: -1
#     api/v2/*: 4
#   ignore:
#     - 404.html
