#!/usr/bin/env python3

import sys


def tint(o):
    return hex(ord(o))


def main():
    print(" ".join(map(lambda x: " ".join(map(tint, x)), sys.argv[1:])))


if __name__ == '__main__':
    main()
